/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.101
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BankAccountUserRead
 */
public class BankAccountUserReadTest {
    private final BankAccountUserRead model = new BankAccountUserRead();

    /**
     * Model tests for BankAccountUserRead
     */
    @Test
    public void testBankAccountUserRead() {
        // TODO: test BankAccountUserRead
    }

    /**
     * Test the property 'iban'
     */
    @Test
    public void ibanTest() {
        // TODO: test iban
    }

    /**
     * Test the property 'bic'
     */
    @Test
    public void bicTest() {
        // TODO: test bic
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'providerName'
     */
    @Test
    public void providerNameTest() {
        // TODO: test providerName
    }

    /**
     * Test the property 'providerCreatedAt'
     */
    @Test
    public void providerCreatedAtTest() {
        // TODO: test providerCreatedAt
    }

    /**
     * Test the property 'providerUpdatedAt'
     */
    @Test
    public void providerUpdatedAtTest() {
        // TODO: test providerUpdatedAt
    }

    /**
     * Test the property 'processorStatus'
     */
    @Test
    public void processorStatusTest() {
        // TODO: test processorStatus
    }

}
