/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.60
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Media
 */
public class MediaTest {
    private final Media model = new Media();

    /**
     * Model tests for Media
     */
    @Test
    public void testMedia() {
        // TODO: test Media
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'extension'
     */
    @Test
    public void extensionTest() {
        // TODO: test extension
    }

    /**
     * Test the property 'filename'
     */
    @Test
    public void filenameTest() {
        // TODO: test filename
    }

    /**
     * Test the property 'fingerprint'
     */
    @Test
    public void fingerprintTest() {
        // TODO: test fingerprint
    }

    /**
     * Test the property 'publicUrl'
     */
    @Test
    public void publicUrlTest() {
        // TODO: test publicUrl
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'b64EncodedTmpFile'
     */
    @Test
    public void b64EncodedTmpFileTest() {
        // TODO: test b64EncodedTmpFile
    }

    /**
     * Test the property 'thumbnail'
     */
    @Test
    public void thumbnailTest() {
        // TODO: test thumbnail
    }

    /**
     * Test the property 'original'
     */
    @Test
    public void originalTest() {
        // TODO: test original
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'offers'
     */
    @Test
    public void offersTest() {
        // TODO: test offers
    }

    /**
     * Test the property 'thumbnailUrl'
     */
    @Test
    public void thumbnailUrlTest() {
        // TODO: test thumbnailUrl
    }

}
