/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tripartie.safecheckout.model.OfferMetadataIndependentWrite;
import com.tripartie.safecheckout.model.OfferPersonaIndependentWrite;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OfferIndependentWrite
 */
public class OfferIndependentWriteTest {
    private final OfferIndependentWrite model = new OfferIndependentWrite();

    /**
     * Model tests for OfferIndependentWrite
     */
    @Test
    public void testOfferIndependentWrite() {
        // TODO: test OfferIndependentWrite
    }

    /**
     * Test the property 'publicUrl'
     */
    @Test
    public void publicUrlTest() {
        // TODO: test publicUrl
    }

    /**
     * Test the property 'redirectUrl'
     */
    @Test
    public void redirectUrlTest() {
        // TODO: test redirectUrl
    }

    /**
     * Test the property 'seller'
     */
    @Test
    public void sellerTest() {
        // TODO: test seller
    }

    /**
     * Test the property 'presetBuyer'
     */
    @Test
    public void presetBuyerTest() {
        // TODO: test presetBuyer
    }

    /**
     * Test the property 'nature'
     */
    @Test
    public void natureTest() {
        // TODO: test nature
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'unitPrice'
     */
    @Test
    public void unitPriceTest() {
        // TODO: test unitPrice
    }

    /**
     * Test the property 'minNegotiableUnitPrice'
     */
    @Test
    public void minNegotiableUnitPriceTest() {
        // TODO: test minNegotiableUnitPrice
    }

    /**
     * Test the property 'allowToNegotiateUnitPrice'
     */
    @Test
    public void allowToNegotiateUnitPriceTest() {
        // TODO: test allowToNegotiateUnitPrice
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'itemCount'
     */
    @Test
    public void itemCountTest() {
        // TODO: test itemCount
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'weightInGram'
     */
    @Test
    public void weightInGramTest() {
        // TODO: test weightInGram
    }

    /**
     * Test the property 'shippingAllowed'
     */
    @Test
    public void shippingAllowedTest() {
        // TODO: test shippingAllowed
    }

    /**
     * Test the property 'handDeliveryAllowed'
     */
    @Test
    public void handDeliveryAllowedTest() {
        // TODO: test handDeliveryAllowed
    }

    /**
     * Test the property 'shippingCarriers'
     */
    @Test
    public void shippingCarriersTest() {
        // TODO: test shippingCarriers
    }

    /**
     * Test the property 'eanCode'
     */
    @Test
    public void eanCodeTest() {
        // TODO: test eanCode
    }

    /**
     * Test the property 'canBeSoldSeparately'
     */
    @Test
    public void canBeSoldSeparatelyTest() {
        // TODO: test canBeSoldSeparately
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
