/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.20
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OfferPostCreationRead
 */
public class OfferPostCreationReadTest {
    private final OfferPostCreationRead model = new OfferPostCreationRead();

    /**
     * Model tests for OfferPostCreationRead
     */
    @Test
    public void testOfferPostCreationRead() {
        // TODO: test OfferPostCreationRead
    }

    /**
     * Test the property 'ulid'
     */
    @Test
    public void ulidTest() {
        // TODO: test ulid
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'presetBuyerId'
     */
    @Test
    public void presetBuyerIdTest() {
        // TODO: test presetBuyerId
    }

    /**
     * Test the property 'sellerId'
     */
    @Test
    public void sellerIdTest() {
        // TODO: test sellerId
    }

}
