/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.81
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tripartie.safecheckout.model.OrganizationMediaCollectionRead;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrganizationCollectionRead
 */
public class OrganizationCollectionReadTest {
    private final OrganizationCollectionRead model = new OrganizationCollectionRead();

    /**
     * Model tests for OrganizationCollectionRead
     */
    @Test
    public void testOrganizationCollectionRead() {
        // TODO: test OrganizationCollectionRead
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'vatNumber'
     */
    @Test
    public void vatNumberTest() {
        // TODO: test vatNumber
    }

    /**
     * Test the property 'commercialRegistryNumber'
     */
    @Test
    public void commercialRegistryNumberTest() {
        // TODO: test commercialRegistryNumber
    }

    /**
     * Test the property 'websiteUrl'
     */
    @Test
    public void websiteUrlTest() {
        // TODO: test websiteUrl
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'logo'
     */
    @Test
    public void logoTest() {
        // TODO: test logo
    }

}
