/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.48
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PersonaAddressRead
 */
public class PersonaAddressReadTest {
    private final PersonaAddressRead model = new PersonaAddressRead();

    /**
     * Model tests for PersonaAddressRead
     */
    @Test
    public void testPersonaAddressRead() {
        // TODO: test PersonaAddressRead
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'zipCode'
     */
    @Test
    public void zipCodeTest() {
        // TODO: test zipCode
    }

    /**
     * Test the property 'cityName'
     */
    @Test
    public void cityNameTest() {
        // TODO: test cityName
    }

    /**
     * Test the property 'firstLine'
     */
    @Test
    public void firstLineTest() {
        // TODO: test firstLine
    }

    /**
     * Test the property 'secondLine'
     */
    @Test
    public void secondLineTest() {
        // TODO: test secondLine
    }

    /**
     * Test the property 'buildingName'
     */
    @Test
    public void buildingNameTest() {
        // TODO: test buildingName
    }

    /**
     * Test the property 'buildingFloor'
     */
    @Test
    public void buildingFloorTest() {
        // TODO: test buildingFloor
    }

    /**
     * Test the property 'gateOrPortalOrInboxCode'
     */
    @Test
    public void gateOrPortalOrInboxCodeTest() {
        // TODO: test gateOrPortalOrInboxCode
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
