/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.102
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tripartie.safecheckout.model.StatisticOutputArraySingleValue;
import com.tripartie.safecheckout.model.StatisticOutputMultipleValue;
import com.tripartie.safecheckout.model.StatisticOutputSingleValue;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StatisticReadDataInner
 */
public class StatisticReadDataInnerTest {
    private final StatisticReadDataInner model = new StatisticReadDataInner();

    /**
     * Model tests for StatisticReadDataInner
     */
    @Test
    public void testStatisticReadDataInner() {
        // TODO: test StatisticReadDataInner
    }

    /**
     * Test the property 'request'
     */
    @Test
    public void requestTest() {
        // TODO: test request
    }

    /**
     * Test the property 'startAt'
     */
    @Test
    public void startAtTest() {
        // TODO: test startAt
    }

    /**
     * Test the property 'endAt'
     */
    @Test
    public void endAtTest() {
        // TODO: test endAt
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

}
