/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.48
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionWalletRead
 */
public class TransactionWalletReadTest {
    private final TransactionWalletRead model = new TransactionWalletRead();

    /**
     * Model tests for TransactionWalletRead
     */
    @Test
    public void testTransactionWalletRead() {
        // TODO: test TransactionWalletRead
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'providerName'
     */
    @Test
    public void providerNameTest() {
        // TODO: test providerName
    }

    /**
     * Test the property 'providerCreatedAt'
     */
    @Test
    public void providerCreatedAtTest() {
        // TODO: test providerCreatedAt
    }

    /**
     * Test the property 'providerUpdatedAt'
     */
    @Test
    public void providerUpdatedAtTest() {
        // TODO: test providerUpdatedAt
    }

    /**
     * Test the property 'processorStatus'
     */
    @Test
    public void processorStatusTest() {
        // TODO: test processorStatus
    }

}
