/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.35
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tripartie.safecheckout.model.TransactionPersonaCollectionRead;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionOfferCollectionRead
 */
public class TransactionOfferCollectionReadTest {
    private final TransactionOfferCollectionRead model = new TransactionOfferCollectionRead();

    /**
     * Model tests for TransactionOfferCollectionRead
     */
    @Test
    public void testTransactionOfferCollectionRead() {
        // TODO: test TransactionOfferCollectionRead
    }

    /**
     * Test the property 'ulid'
     */
    @Test
    public void ulidTest() {
        // TODO: test ulid
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'publicUrl'
     */
    @Test
    public void publicUrlTest() {
        // TODO: test publicUrl
    }

    /**
     * Test the property 'seller'
     */
    @Test
    public void sellerTest() {
        // TODO: test seller
    }

    /**
     * Test the property 'presetBuyer'
     */
    @Test
    public void presetBuyerTest() {
        // TODO: test presetBuyer
    }

    /**
     * Test the property 'nature'
     */
    @Test
    public void natureTest() {
        // TODO: test nature
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'unitPrice'
     */
    @Test
    public void unitPriceTest() {
        // TODO: test unitPrice
    }

    /**
     * Test the property 'minNegotiableUnitPrice'
     */
    @Test
    public void minNegotiableUnitPriceTest() {
        // TODO: test minNegotiableUnitPrice
    }

    /**
     * Test the property 'allowToNegotiateUnitPrice'
     */
    @Test
    public void allowToNegotiateUnitPriceTest() {
        // TODO: test allowToNegotiateUnitPrice
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'itemCount'
     */
    @Test
    public void itemCountTest() {
        // TODO: test itemCount
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'medias'
     */
    @Test
    public void mediasTest() {
        // TODO: test medias
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
