/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.45
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tripartie.safecheckout.model.TransactionOfferCollectionRead;
import com.tripartie.safecheckout.model.TransactionPersonaCollectionRead;
import com.tripartie.safecheckout.model.TransactionQuoteCollectionRead;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionCollectionRead
 */
public class TransactionCollectionReadTest {
    private final TransactionCollectionRead model = new TransactionCollectionRead();

    /**
     * Model tests for TransactionCollectionRead
     */
    @Test
    public void testTransactionCollectionRead() {
        // TODO: test TransactionCollectionRead
    }

    /**
     * Test the property 'ulid'
     */
    @Test
    public void ulidTest() {
        // TODO: test ulid
    }

    /**
     * Test the property 'offer'
     */
    @Test
    public void offerTest() {
        // TODO: test offer
    }

    /**
     * Test the property 'quote'
     */
    @Test
    public void quoteTest() {
        // TODO: test quote
    }

    /**
     * Test the property 'buyerMessage'
     */
    @Test
    public void buyerMessageTest() {
        // TODO: test buyerMessage
    }

    /**
     * Test the property 'buyer'
     */
    @Test
    public void buyerTest() {
        // TODO: test buyer
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'fees'
     */
    @Test
    public void feesTest() {
        // TODO: test fees
    }

    /**
     * Test the property 'supplementalFees'
     */
    @Test
    public void supplementalFeesTest() {
        // TODO: test supplementalFees
    }

    /**
     * Test the property 'providerName'
     */
    @Test
    public void providerNameTest() {
        // TODO: test providerName
    }

    /**
     * Test the property 'providerCreatedAt'
     */
    @Test
    public void providerCreatedAtTest() {
        // TODO: test providerCreatedAt
    }

    /**
     * Test the property 'providerUpdatedAt'
     */
    @Test
    public void providerUpdatedAtTest() {
        // TODO: test providerUpdatedAt
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'totalCharged'
     */
    @Test
    public void totalChargedTest() {
        // TODO: test totalCharged
    }

    /**
     * Test the property 'totalFees'
     */
    @Test
    public void totalFeesTest() {
        // TODO: test totalFees
    }

    /**
     * Test the property 'awaitedParty'
     */
    @Test
    public void awaitedPartyTest() {
        // TODO: test awaitedParty
    }

    /**
     * Test the property 'statusExpiration'
     */
    @Test
    public void statusExpirationTest() {
        // TODO: test statusExpiration
    }

    /**
     * Test the property 'processorStatus'
     */
    @Test
    public void processorStatusTest() {
        // TODO: test processorStatus
    }

}
