/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UnprocessableEntityViolationsInner
 */
public class UnprocessableEntityViolationsInnerTest {
    private final UnprocessableEntityViolationsInner model = new UnprocessableEntityViolationsInner();

    /**
     * Model tests for UnprocessableEntityViolationsInner
     */
    @Test
    public void testUnprocessableEntityViolationsInner() {
        // TODO: test UnprocessableEntityViolationsInner
    }

    /**
     * Test the property 'propertyPath'
     */
    @Test
    public void propertyPathTest() {
        // TODO: test propertyPath
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

}
