/*
 * Safe Checkout
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.23
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.safecheckout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserUpdate
 */
public class UserUpdateTest {
    private final UserUpdate model = new UserUpdate();

    /**
     * Model tests for UserUpdate
     */
    @Test
    public void testUserUpdate() {
        // TODO: test UserUpdate
    }

    /**
     * Test the property 'mainAddress'
     */
    @Test
    public void mainAddressTest() {
        // TODO: test mainAddress
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'publicName'
     */
    @Test
    public void publicNameTest() {
        // TODO: test publicName
    }

    /**
     * Test the property 'roleInCompany'
     */
    @Test
    public void roleInCompanyTest() {
        // TODO: test roleInCompany
    }

    /**
     * Test the property 'birthday'
     */
    @Test
    public void birthdayTest() {
        // TODO: test birthday
    }

    /**
     * Test the property 'intlPhoneNumber'
     */
    @Test
    public void intlPhoneNumberTest() {
        // TODO: test intlPhoneNumber
    }

    /**
     * Test the property 'consentMailAds'
     */
    @Test
    public void consentMailAdsTest() {
        // TODO: test consentMailAds
    }

}
