name: Continuous Delivery (PR)

permissions:
  contents: write
  pull-requests: write

# Controls when the action will run.
on:
  workflow_dispatch:
    branches:
      - main
  schedule:
    - cron: "0 8 * * 1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  generation:
    name: TPDK Generation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Setup node
        with:
          node-version: '18'

      - run: wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        name: Install YQ

      - run: sudo apt install -y jq
        name: Install JQ

      - run: curl ${{ vars.OPENAPI_SCHEMA_HTTP }} -o oas-upstream.json
        name: Download latest OpenAPI

      - run: echo tag=`cat oas-upstream.json | jq .info.version | tr -d '"\n'` >> "$GITHUB_OUTPUT"
        name: Determine schema version
        id: version

      - run: npm install @openapitools/openapi-generator-cli -g
        name: Setup OpenAPI Generator

      - name: Clean Typescript TPDK
        run: rm -fR ./typescript || true

      - name: TPDK for Typescript
        run: openapi-generator-cli generate -g typescript-axios --git-repo-id tpdk-safe-checkout --git-user-id tripartie -o ./typescript -i oas-upstream.json --additional-properties=npmName=@tripartie/safe-checkout,supportsES6=true,stringEnums=true

      - name: Clean Python TPDK
        run: rm -fR ./python || true

      - name: TPDK for Python
        run: openapi-generator-cli generate -g python --git-repo-id tpdk-safe-checkout --git-user-id tripartie -o ./python -i oas-upstream.json --additional-properties=packageName=tpdk_safe_checkout,projectName=tpdk-safe-checkout,packageVersion=${{ steps.version.outputs.tag }},packageUrl=https://pypi.org/project/tpdk-safe-checkout

      - name: Clean Java TPDK
        run: rm -fR ./java || true

      - name: TPDK for Java (8+)
        run: openapi-generator-cli generate -g java --git-repo-id tpdk-safe-checkout --git-user-id tripartie -o ./java -i oas-upstream.json --additional-properties="artifactId=safecheckout,apiPackage=com.tripartie.safecheckout.api,caseInsensitiveResponseHeaders=true,developerOrganization=Tripartie-SAS,developerOrganizationUrl=https://tripartie.com,developerEmail=noc@tripartie.com,artifactVersion=${{ steps.version.outputs.tag }},groupId=com.tripartie,invokerPackage=com.tripartie.safecheckout,modelPackage=com.tripartie.safecheckout.model,licenseName=Apache-2.0,licenseUrl=https://raw.githubusercontent.com/tripartie/tpdk-safe-checkout/main/LICENSE,scmConnection=scm:git:git@github.com:tripartie/tpdk-safe-checkout.git,scmDeveloperConnection=scm:git:git@github.com:tripartie/tpdk-safe-checkout.git,scmUrl=https://github.com/tripartie/tpdk-safe-checkout,artifactUrl=https://github.com/tripartie/tpdk-safe-checkout,developerName=Tripartie,useSingleRequestParameter=true"

      - name: Remove duplicate Java workflow
        run: rm -f ./java/.github/workflows/maven.yml || true

      - name: Cleanup
        run: rm -f oas-upstream.json openapitools.json

      - name: Patch license (Typescript)
        run: sed -i 's/Unlicense/Apache-2\.0/g' ./typescript/package.json

      - name: Patch license (Python)
        run: sed -i 's/NoLicense/Apache-2\.0/g' ./python/pyproject.toml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: sync upstream changes - openapi generation - ${{ steps.version.outputs.tag }}
          title: "[tpdk][${{ steps.version.outputs.tag }}] sync from upstream openapi changes"
